server:
  port: 8090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: inscription-service-route
          uri: lb://INSCRIPTION-SERVICE
          predicates:
            - Path=/inscriptions/**
    eureka:
        client:
            defaultZone: http://localhost:8761/eureka/
        instance:
            prefer-ip-address: true