package ma.emsi.defenseservice.enums;

public enum DocumentType {
    MANUSCRIPT, ANTI_PLAGIARISM_REPORT, PUBLICATIONS_REPORT,
    TRAINING_CERTIFICATES, AUTHORIZATION_LETTER, JURY_REPORT, PROCES_VERBAL
}

